apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: registry.k8s.io/cloud-provider-ibm/ibm-powervs-block-csi-driver
  newTag: v0.7.0
- name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: v5.0.1
- name: registry.k8s.io/sig-storage/csi-attacher
  newTag: v4.6.1
- name: registry.k8s.io/sig-storage/csi-resizer
  newTag: v1.9.4
- name: registry.k8s.io/sig-storage/livenessprobe
  newTag: v2.12.0
- name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: v2.10.1
resources:
- ../../base
